"""Reading secrets from files.

Secrets are mounted as files (``/run/secrets/...``) and referenced by path in settings, never
passed as environment variable values (ADR 0013).
"""

import base64
import binascii
from pathlib import Path


class SecretError(RuntimeError):
    """A required secret is missing or empty. Startup must stop; there are no defaults."""


def read_secret(path: Path) -> str:
    """Return the secret stored in ``path``, without the trailing newline editors add."""
    try:
        value = path.read_text(encoding="utf-8").rstrip("\r\n")
    except FileNotFoundError as error:
        raise SecretError(f"secret file not found: {path}") from error
    if not value:
        raise SecretError(f"secret file is empty: {path}")
    return value


def read_key(path: Path, *, length: int = 32) -> bytes:
    """Return a binary key stored as unpadded base64url text (as generated by the installer)."""
    text = read_secret(path)
    try:
        key = base64.urlsafe_b64decode(text + "=" * (-len(text) % 4))
    except (binascii.Error, ValueError) as error:
        raise SecretError(f"key file is not base64url: {path}") from error
    if len(key) != length:
        raise SecretError(f"key in {path} must be {length} bytes, found {len(key)}")
    return key
