"""Rendering an installation's files from ``synapse.toml`` (ADR 0012).

Output, in ``paths.render_dir``:

- ``compose.yml``: the services, hardened as in docs/deployment.md, sized by hardware tier.
- ``caddy/tls.caddy``: the TLS directive for the chosen mode.
- ``manifest.json``: the SHA-256 of each rendered file and of the configuration, so ``doctor``
  can tell when someone edited a file by hand or changed the configuration without rendering.

Rendering is a pure function of the configuration; writing is separate so tests and ``doctor``
can compare without touching the disk.
"""

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from synapsectl.config import SynapseConfig, Tier, TlsMode, dump
from synapsectl.secrets import DATABASE_ROLES

# A tmpfs mount point inside the containers, not a file created on the host.
CONTAINER_TMP = ["/tmp"]  # noqa: S108

HEADER = "# Generated by synapsectl from synapse.toml. Do not edit; run: synapsectl render\n"

# Memory limits per tier (ADR 0002, docs/research/04-architecture.md). Model servers are added
# with the knowledge base.
MEMORY = {
    Tier.CPU_16: {"db": "2560m", "api": "768m", "web": "128m"},
    Tier.CPU_32: {"db": "6g", "api": "1536m", "web": "128m"},
    Tier.GPU: {"db": "6g", "api": "1536m", "web": "128m"},
}


@dataclass(frozen=True)
class Rendered:
    files: dict[str, str]  # relative path -> content

    def manifest(self, config: SynapseConfig) -> str:
        entry = {name: _sha256(content) for name, content in sorted(self.files.items())}
        return json.dumps({"config": _sha256(dump(config)), "files": entry}, indent=2) + "\n"


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _hardened(service: dict[str, Any]) -> dict[str, Any]:
    return {
        **service,
        "read_only": True,
        "cap_drop": ["ALL"],
        "security_opt": ["no-new-privileges:true"],
        "networks": ["internal"],
    }


def compose(config: SynapseConfig) -> dict[str, Any]:
    version = config.images.version
    memory = MEMORY[config.hardware]
    database = {"SYNAPSE_DB_HOST": "db", "SYNAPSE_DB_PORT": "5432", "SYNAPSE_DB_NAME": "synapse"}
    app = f"synapse-app:{version}"
    services: dict[str, Any] = {
        "db": {
            "image": f"synapse-postgres:{version}",
            "environment": {"POSTGRES_PASSWORD_FILE": "/run/secrets/postgres_superuser"},
            "secrets": ["postgres_superuser"],
            "volumes": ["db-data:/var/lib/postgresql"],
            "networks": ["internal"],
            "mem_limit": memory["db"],
            "restart": "unless-stopped",
            "healthcheck": {
                "test": ["CMD", "pg_isready", "-U", "postgres"],
                "interval": "5s",
                "timeout": "3s",
                "retries": 20,
            },
        },
        "bootstrap": _hardened(
            {
                "image": app,
                "command": [
                    "db",
                    "bootstrap",
                    "--admin-conninfo-file=/run/secrets/admin_conninfo",
                    "--secrets-dir=/run/secrets",
                ],
                "environment": database,
                "secrets": ["admin_conninfo", *(f"db_{role}" for role in DATABASE_ROLES)],
                "depends_on": {"db": {"condition": "service_healthy"}},
                "restart": "no",
                "tmpfs": CONTAINER_TMP,
            }
        ),
        "migrate": _hardened(
            {
                "image": app,
                "command": ["db", "migrate"],
                "environment": {
                    **database,
                    "SYNAPSE_DB_USER": "synapse_migrator",
                    "SYNAPSE_DB_PASSWORD_FILE": "/run/secrets/db_synapse_migrator",
                },
                "secrets": ["db_synapse_migrator"],
                "depends_on": {"bootstrap": {"condition": "service_completed_successfully"}},
                "restart": "no",
                "tmpfs": CONTAINER_TMP,
            }
        ),
        "api": _hardened(
            {
                "image": app,
                "command": ["api"],
                "environment": {
                    **database,
                    "SYNAPSE_TENANT_ID": str(config.instance.tenant_id),
                    "SYNAPSE_API_HOST": "0.0.0.0",  # noqa: S104  (inside the container network)
                    "SYNAPSE_API_PORT": "8000",
                    "SYNAPSE_DB_USER": "synapse_api",
                    "SYNAPSE_DB_PASSWORD_FILE": "/run/secrets/db_synapse_api",
                    "SYNAPSE_CSRF_KEY_FILE": "/run/secrets/csrf_key",
                    "SYNAPSE_TOTP_KEY_FILE": "/run/secrets/totp_key",
                    "SYNAPSE_AUDIT_SIGNING_KEY_FILE": "/run/secrets/audit_signing_key",
                    "SYNAPSE_TRUSTED_PROXY_IPS": config.network.subnet,
                    # Passkeys are bound to this address (docs/design/identity.md).
                    "SYNAPSE_PUBLIC_URL": f"https://{site_address(config)}",
                },
                "secrets": ["db_synapse_api", "csrf_key", "totp_key", "audit_signing_key"],
                # Uploaded files; backed up together with the database (ADR 0003).
                "volumes": ["blobs:/var/lib/synapse/blobs"],
                "depends_on": {"migrate": {"condition": "service_completed_successfully"}},
                "mem_limit": memory["api"],
                "restart": "unless-stopped",
                "tmpfs": CONTAINER_TMP,
                "healthcheck": {
                    "test": [
                        "CMD",
                        "python",
                        "-c",
                        "import urllib.request; "
                        "urllib.request.urlopen('http://127.0.0.1:8000/healthz', timeout=3)",
                    ],
                    "interval": "10s",
                    "timeout": "5s",
                    "retries": 6,
                },
            }
        ),
        "web": _hardened(_web(config, memory["web"])),
    }
    secret_names = {name for service in services.values() for name in service.get("secrets", [])}
    return {
        "name": f"synapse-{config.instance.slug}",
        "services": services,
        "networks": {"internal": {"ipam": {"config": [{"subnet": config.network.subnet}]}}},
        "secrets": {
            name: {"file": str(config.paths.secrets_dir / name)} for name in sorted(secret_names)
        },
        "volumes": {"db-data": {}, "blobs": {}, "caddy-data": {}},
    }


def site_address(config: SynapseConfig) -> str:
    """Host name, with the HTTPS port when it is not 443: the address users open."""
    https = config.network.https_port
    return config.instance.hostname if https == 443 else f"{config.instance.hostname}:{https}"  # noqa: PLR2004


def _web(config: SynapseConfig, memory: str) -> dict[str, Any]:
    http, https = config.network.http_port, config.network.https_port
    service: dict[str, Any] = {
        "image": f"synapse-web:{config.images.version}",
        "environment": {
            # The HTTPS port is written into the address when it is not 443, so Caddy listens on
            # it and puts it into redirects (see deploy/web/Caddyfile).
            "SYNAPSE_SITE_ADDRESS": site_address(config),
            "SYNAPSE_HTTP_PORT": str(http),
        },
        # The same port numbers inside and outside, so Caddy's redirects and certificates use
        # the addresses clients actually see.
        "ports": [f"{http}:{http}", f"{https}:{https}"],
        # Lets the unprivileged Caddy bind ports below 1024 without any capability.
        "sysctls": {"net.ipv4.ip_unprivileged_port_start": str(min(http, https))},
        "volumes": [
            "caddy-data:/data",
            f"{config.paths.render_dir / 'caddy'}:/etc/caddy/site.d:ro",
        ],
        "tmpfs": ["/config:uid=10001,gid=10001"],
        "depends_on": {"api": {"condition": "service_healthy"}},
        "mem_limit": memory,
        "restart": "unless-stopped",
        "healthcheck": {
            # Caddy's own liveness port (deploy/web/Caddyfile); it is not published.
            "test": ["CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1:8099/"],
            "interval": "10s",
            "timeout": "5s",
            "retries": 6,
        },
    }
    if TlsMode(config.tls.mode) is TlsMode.PROVIDED:
        service["secrets"] = ["tls_certificate", "tls_private_key"]
    return service


def tls_snippet(config: SynapseConfig) -> str:
    mode = TlsMode(config.tls.mode)
    if mode is TlsMode.INTERNAL:
        directive = "tls internal"
    elif mode is TlsMode.PROVIDED:
        directive = "tls /run/secrets/tls_certificate /run/secrets/tls_private_key"
    else:
        directive = f"tls {config.tls.email}"
    return HEADER + directive + "\n"


def render(config: SynapseConfig) -> Rendered:
    compose_text = HEADER + yaml.safe_dump(compose(config), sort_keys=False, width=100)
    return Rendered(files={"compose.yml": compose_text, "caddy/tls.caddy": tls_snippet(config)})


def write(config: SynapseConfig, rendered: Rendered) -> list[Path]:
    root = config.paths.render_dir
    written = []
    for name, content in rendered.files.items():
        path = root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(path)
    (root / "manifest.json").write_text(rendered.manifest(config), encoding="utf-8")
    return written
