"""Create local development secrets under .dev/secrets/ (git-ignored).

Existing files are kept, so running it again is harmless. Production secrets are generated by
the installer on the customer's machine and never by this script (ADR 0013).

Permissions: the directory is 0700, so no other user on the machine can reach the files, and the
files are 0644, so the containers can read them. They run as their own users (postgres 999, the
application 10001), and on Linux a bind-mounted file keeps its host owner. Docker Desktop on
macOS presents the file as owned by the container user, which hides the problem there.

Usage: python3 tools/dev_secrets.py
"""

import secrets
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SECRETS = ROOT / ".dev" / "secrets"
DEV_DB_PORT = 55432  # see deploy/compose.dev.yml

# Each file holds 32 random bytes as unpadded base64url text.
SECRET_FILES = (
    "db_synapse_migrator",
    "db_synapse_api",
    "db_synapse_worker",
    "db_synapse_scheduler",
    "csrf_key",
    "totp_key",
    "audit_signing_key",
    # The model servers' API keys (deploy/compose.stack.yml, "models" profile).
    "embed_key",
    "rerank_key",
    "chat_key",
)


def write_once(path: Path, value: str) -> None:
    if path.exists():
        return
    path.write_text(value + "\n", encoding="utf-8")


def main() -> int:
    SECRETS.mkdir(parents=True, exist_ok=True)
    write_once(SECRETS / "postgres_superuser", secrets.token_urlsafe(32))
    for name in SECRET_FILES:
        write_once(SECRETS / name, secrets.token_urlsafe(32))

    superuser = (SECRETS / "postgres_superuser").read_text(encoding="utf-8").strip()
    write_once(
        SECRETS / "admin_conninfo",
        f"postgresql://postgres:{superuser}@127.0.0.1:{DEV_DB_PORT}/postgres",
    )
    # The same, as seen from inside the full stack (deploy/compose.stack.yml).
    write_once(
        SECRETS / "admin_conninfo_stack", f"postgresql://postgres:{superuser}@db:5432/postgres"
    )
    SECRETS.chmod(0o700)
    for path in SECRETS.iterdir():
        path.chmod(0o644)
    print(f"development secrets are in {SECRETS.relative_to(ROOT)}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
